name: flutter_getx_starter
description: A Flutter Starter Package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  get:
  google_fonts:
  shared_preferences:
  flutter_secure_storage:
  intl:
  image_picker:
  json_annotation: ^4.5.0

  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/config/
    - assets/themes/
    - assets/locale/
    - assets/locale/ar/
    - assets/locale/en/
